### ISSUE TITLE
How to Add custom operator . 

### ISSUE THREAD

**Issue by v1xingyue** [nikunjy/rules#13]
How Can I add my own custom operator . 
Then I Can extend this rule engine more powerful.

**Comment by nikunjy** [comment]
You can add it here https://github.com/nikunjy/rules/blob/master/cmd/JsonQuery.g4
What will the `.` do ?

**Comment by nikunjy** [comment]
Right now `.` is being used for JSON Path

**Comment by v1xingyue** [comment]
> You can add it here https://github.com/nikunjy/rules/blob/master/cmd/JsonQuery.g4
> What will the `.` do ?

Thank you , I'll try see this file .
Sorry For my poor english .
I just want to add my own custom operaor for example  'reg' , Not "." .

**Comment by v1xingyue** [comment]
As I can see parser dir files list : 

```
JsonQuery.interp          JsonQueryLexer.tokens     float_operation.go        jsonquery_parser.go       nester_error.go           string_operation.go
JsonQuery.tokens          bool_operation.go         int_operation.go          jsonquery_visitor.go      null_operation.go         version_operation.go
JsonQueryLexer.interp     evaluate.go               jsonquery_lexer.go        jsonquery_visitor_impl.go operation.go
```

These files : 
```
JsonQuery.interp   JsonQuery.tokens   JsonQueryLexer.interp      JsonQueryLexer.tokens  
jsonquery_lexer.go   

 ``` 
are generated by antlr4 through JsonQuery.g4 . 

Left Go Code files: 
```  
 jsonquery_parser.go       nester_error.go    

jsonquery_visitor.go       jsonquery_visitor_impl.go operation.go  

float_operation.go     string_operation.go    bool_operation.go         int_operation.go          null_operation.go         
version_operation.go  

 evaluate.go                  
```
What does it mean ?  

--- 

Would you please help me create this project from scratch by one Single g4 file ?

**Comment by nikunjy** [comment]
Please pull the recent master. I have moved the grammar file in the parser folder. 
I have also updated the [instructions](https://github.com/nikunjy/rules/blob/master/README.md#how-to-extend-the-grammar) in the README.md on how to extend the grammar 

Once you setup antlr, edit the grammar file and compile your parser, it will generate some files like 
` jsonquery_parser.go  jsonquery_visitor.go  .. .....etc`

Those are generated by antlr, but then you will have to write an implementation for your operator. That will probably [here](https://github.com/nikunjy/rules/blob/master/parser/jsonquery_visitor_impl.go)

You can take a look at one of the [example commit](https://github.com/nikunjy/rules/commit/3563ab1a59939a4056163194a898c96e5118e645) I did for extending the grammar. 

It would be outside the scope of this discussion to explain how that file is written I am afraid, you will have to read the source for `jsonquery_visitor_impl.go` to better understand how to write "visit" for your operator. 

You will then also have to write an implementation of how the operator is evaluated for a float, int, string, etc in the string_operation.go, bool_operation.go .... etc

Give it a shot and if it doesn't work let me know, I might be able to extend it.

**Comment by v1xingyue** [comment]
> Please pull the recent master. I have moved the grammar file in the parser folder.
> I have also updated the [instructions](https://github.com/nikunjy/rules/blob/master/README.md#how-to-extend-the-grammar) in the README.md on how to extend the grammar
> 
> Once you setup antlr, edit the grammar file and compile your parser, it will generate some files like
> ` jsonquery_parser.go jsonquery_visitor.go .. .....etc`
> 
> Those are generated by antlr, but then you will have to write an implementation for your operator. That will probably [here](https://github.com/nikunjy/rules/blob/master/parser/jsonquery_visitor_impl.go)
> 
> You can take a look at one of the [example commit](https://github.com/nikunjy/rules/commit/3563ab1a59939a4056163194a898c96e5118e645) I did for extending the grammar.
> 
> It would be outside the scope of this discussion to explain how that file is written I am afraid, you will have to read the source for `jsonquery_visitor_impl.go` to better understand how to write "visit" for your operator.
> 
> You will then also have to write an implementation of how the operator is evaluated for a float, int, string, etc in the string_operation.go, bool_operation.go .... etc
> 
> Give it a shot and if it doesn't work let me know, I might be able to extend it.

That's great. 
Thank you very much .
