### ISSUE TITLE
How can I parse array?

### ISSUE THREAD

**Issue by ParkDerkYoul** [nikunjy/rules#16]
Hi, nikunjy
Thank you for the great package.

I have a question. I want to evaluate array.

ex )
{
 "class":"A",
  "student:[{
    "name","jon",
    "age":"30"
   },
  {
    "name":"park",
    "age":"31"
  }
]}
rule := "student[0].name == \"json\" and student[0].age < \"31\""
parser.Evaluate(rule, obj)
-> I want true result but false.
How can I parse array?

**Comment by ysBayram** [comment]
I didn't try but it seems your rule and result true. You may attention on rule ; """ name == "json" """ maybe you should try """ name == "jon"  """

**Comment by ParkDerkYoul** [comment]
hi, @ysBayram.
It was my mistake. I had tried """ name == "jon" """..

**Comment by nikunjy** [comment]
Did it work @ParkDerkYoul  or do you still need help ?

**Comment by ParkDerkYoul** [comment]
@nikunjy 
Thank you for your attention!! I was solve.
