### ISSUE TITLE
it seems antlr library changed

### ISSUE THREAD

**Issue by asaqib27** [nikunjy/rules#22]
I am receiving this exception and it seems antlr dependency has updated and deprecated/removed this method.

```
jsonquery_lexer.go:152:34: lexerDeserializer.DeserializeFromUInt16 undefined (type *antlr.ATNDeserializer has no field or method DeserializeFromUInt16)
```

**Comment by nikunjy** [comment]
It is probable it has changed. What are you trying to do ?

**Comment by nikunjy** [comment]
Either way I upgraded the antlr version. 
https://github.com/nikunjy/rules/pull/24
