### ISSUE TITLE
rule parse bug

### ISSUE THREAD

**Issue by JohnnyTing** [nikunjy/rules#32]
the below return false
case1:
`parser.Evaluate("x < 2 and ( y > 4 or z == true )",
		map[string]interface{}{
			"x": 1,
			"y": 3,
			"z": true,
		},
	)`

and the below return true
case2:
`parser.Evaluate("x < 2 and ( y > 4 or z == true)",
		map[string]interface{}{
			"x": 1,
			"y": 3,
			"z": true,
		},
	)`

in case 1, the end of the rule contains ' ',  and this is bug?

**Comment by nikunjy** [comment]
Yes that does feel like a bug.

**Comment by nikunjy** [comment]
Okay so I looked into it and actually neither `( y > 4 or z == true)` or `( y > 4 or z === true )` is allowed. It is just that the parser eats the error silently in the first case. Ideally it should be `(y > 4 or z == true)`. I think it can be extended though.

**Comment by nikunjy** [comment]
Fixed in https://github.com/nikunjy/rules/releases/tag/v1.5.0 
@JohnnyTing
