### ISSUE TITLE
import "github.com/nikunjy/rules" is a program, not an importable package

### ISSUE THREAD

**Issue by dgeraskov** [nikunjy/rules#9]
I believe this is happening because you have main.go#main in your repository.

**Comment by nikunjy** [comment]
Yes it is because of that, maybe I should change the documentation to explicitly say to use the package 
`github.com/nikunjy/rules/parser`

I could move the main.go in a separate package also. I will consider it, thanks for the suggestion

**Comment by nikunjy** [comment]
I have moved main.go to its own package and changed README.md to call out what to import.
